"""E2E tests for `awf start` pipeline execution — happy path, blocked, auto-done."""
import re
import subprocess
import time
from pathlib import Path

from conftest import run_awf


def _create_todo(proj: Path, todo_id: str = "TODO-0001"):
    """Create a TODO in inbox so the orchestrator can find it.

    Also pre-creates APPROVE-TODO-NNNN.ready signal so BD-8 auto-mode
    commit gate doesn't block pipeline. Tests run with --auto, which
    (per BD-8) requires explicit approval before commit_and_next commits.
    """
    inbox = proj / ".agentic/inbox"
    inbox.mkdir(exist_ok=True)
    (inbox / f"{todo_id}.md").write_text(f"# {todo_id}\nstub task\n")
    (inbox / f"{todo_id}.ready").write_text(f"signal: TASK_READY\ntask_id: {todo_id}\n")
    # BD-8: pre-authorize commit so pipeline doesn't wait in --auto mode
    (inbox / f"APPROVE-{todo_id}.ready").write_text(
        f"signal: APPROVE\ntask_id: {todo_id}\n"
    )
    (proj / ".agentic/context").mkdir(exist_ok=True)


class TestPipeline:

    def test_pipeline_happy_path(self, initialized_project: Path, awf_bin: str, awf_env: dict):
        """Pipeline runs end-to-end with stub writing DONE signal."""
        _create_todo(initialized_project)

        result = run_awf(
            awf_bin, ["start", "--auto"],
            cwd=initialized_project, env=awf_env, input_data=b"", timeout=60
        )

        # The stub writes DONE-TODO-0001.ready
        assert (initialized_project / ".agentic/outbox/DONE-TODO-0001.ready").exists(), \
            f"Expected DONE signal. stdout={result.stdout.decode()!r} stderr={result.stderr.decode()!r}"

    def test_pipeline_blocked_then_replan(self, initialized_project: Path, awf_bin: str, awf_env: dict):
        """When stub writes BLOCKED, pipeline detects it and exits non-zero."""
        _create_todo(initialized_project)
        awf_env["AWF_TEST_OPENCODE_BEHAVIOR"] = "blocked"

        result = run_awf(
            awf_bin, ["start", "--auto"],
            cwd=initialized_project, env=awf_env, input_data=b"", timeout=60
        )

        # BLOCKED signal should exist
        assert (initialized_project / ".agentic/outbox/BLOCKED-TODO-0001.ready").exists(), \
            f"Expected BLOCKED signal. stderr={result.stderr.decode()!r}"

        # Pipeline should NOT silently succeed — exit code reflects BLOCKED state
        assert result.returncode != 0, "Pipeline should exit non-zero on BLOCKED"

    def test_pipeline_orphan_auto_done(self, initialized_project: Path, awf_bin: str, awf_env: dict):
        """Auto-DONE triggers when verify passes + work evidence present + no signal."""
        _create_todo(initialized_project)

        # Write baseline file so detect_work_evidence has a reference
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=initialized_project, capture_output=True, text=True
        ).stdout.strip()
        (initialized_project / ".agentic/context/BASELINE-TODO-0001.sha").write_text(sha + "\n")

        # Configure verification to always pass — attempt_auto_done checks
        # typecheck_cmd, build_cmd, and test_cmd; all non-empty ones must pass.
        cfg = (initialized_project / ".agentic/config.yaml").read_text()
        cfg = re.sub(r'typecheck_cmd:\s*"[^"]*"', 'typecheck_cmd: "true"', cfg)
        cfg = re.sub(r'test_cmd:\s*"[^"]*"', 'test_cmd: "true"', cfg)
        cfg = re.sub(r'lint_cmd:\s*"[^"]*"', 'lint_cmd: ""', cfg)
        (initialized_project / ".agentic/config.yaml").write_text(cfg)

        awf_env["AWF_TEST_OPENCODE_BEHAVIOR"] = "auto_done"

        result = run_awf(
            awf_bin, ["start", "--auto"],
            cwd=initialized_project, env=awf_env, input_data=b"", timeout=60
        )

        # Auto-DONE should have been synthesized
        done_ready = initialized_project / ".agentic/outbox/DONE-TODO-0001.ready"
        assert done_ready.exists(), \
            f"Expected auto-DONE signal. stderr={result.stderr.decode()!r} stdout={result.stdout.decode()!r}"

        # Content should indicate it was auto-generated
        done_md = initialized_project / ".agentic/outbox/DONE-TODO-0001.md"
        if done_md.exists():
            content = done_md.read_text()
            assert "AUTO-GENERATED by orchestrator" in content, \
                f"Expected AUTO-GENERATED marker in DONE report. Got: {content[:200]}"

    def test_pipeline_background_mode(self, initialized_project: Path, awf_bin: str, awf_env: dict):
        """awf start --background returns immediately and runs the pipeline detached."""
        _create_todo(initialized_project)
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=initialized_project, capture_output=True, text=True
        ).stdout.strip()
        (initialized_project / ".agentic/context/BASELINE-TODO-0001.sha").write_text(sha + "\n")

        awf_env["AWF_TEST_OPENCODE_BEHAVIOR"] = "done"

        result = run_awf(
            awf_bin, ["start", "--background", "--auto"],
            cwd=initialized_project, env=awf_env, input_data=b"",
            timeout=15,
        )

        stdout = result.stdout.decode()
        assert "running in background" in stdout, f"Expected background banner. stdout={stdout!r}"
        assert "PID" in stdout

        log_file = initialized_project / ".agentic/logs/awf-start.out"
        assert log_file.exists(), f"Log file not created: {log_file}"

        done_file = initialized_project / ".agentic/outbox/DONE-TODO-0001.ready"
        deadline = time.time() + 30
        while time.time() < deadline:
            if done_file.exists():
                break
            time.sleep(1)

        assert done_file.exists(), (
            f"Detached pipeline did not write DONE within 30s. "
            f"Log content:\n{log_file.read_text() if log_file.exists() else '<no log>'}"
        )
