"""Write .agentic/pipelines/default.yaml from form team selection."""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

log = logging.getLogger(__name__)


def _stage_yaml(name: str, role: str, action: str, **extra: Any) -> dict[str, Any]:
    """Build a stage dict for YAML serialization."""
    stage = {"name": name, "role": role, "action": action}
    stage.update(extra)
    return stage


def build_pipeline_stages(team_order: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build ordered pipeline stages from team selection.

    Args:
        team_order: list of team member dicts (from form's team_config JSON).
            Each dict has at least: {agent: <role_name>, type: 'default'|'custom', ...}.

    Returns:
        List of stage dicts: plan + team stages + verify.
    """
    stages: list[dict[str, Any]] = [
        _stage_yaml(
            "plan",
            "supervisor",
            "create_todo",
            description="Supervisor studies the plan and creates a TODO",
        ),
    ]

    seen_roles: set[str] = set()
    for member in team_order:
        role = str(member.get("agent", "")).strip()
        if not role:
            continue
        if role in seen_roles:
            log.warning("Duplicate role %r in team_order — skipping", role)
            continue
        seen_roles.add(role)
        stages.append(
            _stage_yaml(
                name=role,
                role=role,
                action="execute_todo",
                description=f"{role} executes the TODO",
                on_blocked="escalate",
                max_retries=3,
            )
        )

    stages.append(
        _stage_yaml(
            "verify",
            "supervisor",
            "verify_result",
            description="Supervisor verifies the result",
            on_approved="commit_and_next",
            on_rejected="replan",
        )
    )

    return stages


def write_pipeline(team_order: list[dict[str, Any]], project_dir: Path) -> Path | None:
    """Write .agentic/pipelines/default.yaml from team selection.

    Args:
        team_order: form team_config list (ordered).
        project_dir: absolute path to awf project (from BD-6 form data).

    Returns:
        Path to written file, or None if project_dir has no .agentic/.
    """
    if not project_dir or not (project_dir / ".agentic").is_dir():
        log.debug("No project_dir or no .agentic/ — skip pipeline write")
        return None

    pipelines_dir = project_dir / ".agentic" / "pipelines"
    pipelines_dir.mkdir(parents=True, exist_ok=True)

    stages = build_pipeline_stages(team_order)
    pipeline_dict: dict[str, Any] = {
        "name": "default",
        "description": "Generated by agent-workflow-ui from project-setup form",
        "stages": stages,
    }

    target = pipelines_dir / "default.yaml"
    if target.exists():
        backup = pipelines_dir / "default.yaml.bak"
        target.rename(backup)
        log.info("Backed up existing pipeline to %s", backup)

    content = yaml.safe_dump(
        pipeline_dict, default_flow_style=False, allow_unicode=True, sort_keys=False
    )
    target.write_text(content, encoding="utf-8")
    log.info("Wrote pipeline with %d team stages to %s", len(stages) - 2, target)
    return target
