"""Write .agentic/pipelines/default.yaml from form team selection.

BD-29: pipeline.yaml no longer has `action:` field — awf computes kind from
position. Format is just role + policies.

Stages:
- First stage: supervisor (kind="plan" computed automatically)
- Last stage: supervisor (kind="verify" computed automatically)
- Middle stages: user-selected agent roles (kind="execute")
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

log = logging.getLogger(__name__)


def _stage_yaml(name: str, role: str, **extra: Any) -> dict[str, Any]:
    """Build a stage dict for YAML serialization.

    BD-29: no `action` field — kind is computed from position by awf.
    """
    stage: dict[str, Any] = {"name": name, "role": role}
    stage.update(extra)
    return stage


def build_pipeline_stages(team_order: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build ordered pipeline stages from team selection.

    Wraps the user's team with supervisor at both ends (always plan→agents→verify).

    Args:
        team_order: list of team member dicts (from form's team_config JSON).
            Each dict has at least: {agent: <role_name>, type: 'default'|'custom', ...}.

    Returns:
        List of stage dicts: [plan(supervisor)] + [team stages] + [verify(supervisor)].

    Raises:
        ValueError: if team_order is empty or has no valid role entries
            (empty pipeline would be plan→verify with no work — useless).
    """
    # BD-29 guard: validate team is non-empty BEFORE wrapping with supervisor.
    # Belt-and-suspenders — UI form should also disable Submit on empty team.
    valid_roles = [
        str(m.get("agent") or m.get("role") or "").strip()
        for m in team_order
    ]
    valid_roles = [r for r in valid_roles if r]
    if not valid_roles:
        raise ValueError(
            "Cannot build pipeline with zero agent roles — at least one "
            "role is required between supervisor plan and verify."
        )

    stages: list[dict[str, Any]] = [
        _stage_yaml(
            "plan",
            "supervisor",
            description="Supervisor studies the plan and creates a TODO",
        ),
    ]

    seen_roles: set[str] = set()
    for member in team_order:
        role = str(member.get("agent") or member.get("role") or "").strip()
        if not role:
            continue
        if role in seen_roles:
            log.warning("Duplicate role %r in team_order — skipping", role)
            continue
        seen_roles.add(role)
        stages.append(
            _stage_yaml(
                name=role,
                role=role,
                description=f"{role} executes the TODO",
                on_blocked="escalate",
                max_retries=3,
            )
        )

    stages.append(
        _stage_yaml(
            "verify",
            "supervisor",
            description="Supervisor verifies the result",
            on_approved="commit_and_next",
            on_rejected="replan",
        )
    )

    return stages


def write_pipeline(team_order: list[dict[str, Any]], project_dir: Path) -> Path | None:
    """Write .agentic/pipelines/default.yaml from team selection.

    Args:
        team_order: form team_config list (ordered).
        project_dir: absolute path to awf project (from BD-6 form data).

    Returns:
        Path to written file, or None if project_dir has no .agentic/.
    """
    if not project_dir or not (project_dir / ".agentic").is_dir():
        log.debug("No project_dir or no .agentic/ — skip pipeline write")
        return None

    pipelines_dir = project_dir / ".agentic" / "pipelines"
    pipelines_dir.mkdir(parents=True, exist_ok=True)

    stages = build_pipeline_stages(team_order)
    pipeline_dict: dict[str, Any] = {
        "name": "default",
        "description": "Generated by agent-workflow-ui from project-setup form",
        "stages": stages,
    }

    target = pipelines_dir / "default.yaml"
    if target.exists():
        backup = pipelines_dir / "default.yaml.bak"
        try:
            target.rename(backup)
            log.info("Backed up existing pipeline to %s", backup)
        except OSError:
            pass

    content = yaml.safe_dump(
        pipeline_dict, default_flow_style=False, allow_unicode=True, sort_keys=False
    )
    # M3 fix: atomic write (was direct write_text — crash corrupts pipeline.yaml).
    from .state import _atomic_write_text
    _atomic_write_text(target, content)
    log.info("Wrote pipeline with %d team stages to %s", len(stages) - 2, target)
    return target
