"""Verify commands and auto-DONE logic."""
from __future__ import annotations

import subprocess
from pathlib import Path

from . import config as cfg_mod
from . import git_utils


def detect_work_evidence(project_dir: str | Path, baseline_sha: str) -> bool:
    """Return True if there are tracked changes OR untracked files vs baseline."""
    cwd = Path(project_dir)
    if not git_utils.is_git_repo(cwd):
        return False
    if git_utils.has_diff(cwd, baseline_sha):
        return True
    if git_utils.untracked_files(cwd):
        return True
    return False


def run_verify_commands(config: dict) -> bool:
    """Run each non-empty verify command. Returns True if all pass."""
    cmd_keys = ["test_cmd", "lint_cmd", "typecheck_cmd", "build_cmd"]
    cmds = []
    for key in cmd_keys:
        val = cfg_mod.get(config, f"verification.{key}", "")
        if val:
            cmds.append(val)

    if not cmds:
        return False  # no commands configured → can't verify

    for cmd in cmds:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, check=False,
        )
        if result.returncode != 0:
            return False
    return True


def attempt_auto_done(
    project_dir: str | Path,
    todo_id: str,
    config: dict,
    baseline_sha: str,
) -> bool:
    """Try to synthesize DONE when worker left no signal but work + verify pass.

    Returns True if DONE was synthesized.
    """
    cwd = Path(project_dir)
    outbox = cwd / ".agentic" / "outbox"

    # Check automation.auto_done opt-out
    auto_done_enabled = cfg_mod.get(config, "automation.auto_done", "true")
    if isinstance(auto_done_enabled, str):
        auto_done_enabled = auto_done_enabled.lower()
    if auto_done_enabled not in ("true", "1"):
        return False

    # Must have work evidence
    if not detect_work_evidence(cwd, baseline_sha):
        return False

    # Verify commands must all pass
    if not run_verify_commands(config):
        return False

    # Synthesize DONE
    done_md = outbox / f"DONE-{todo_id}.md"
    done_md.write_text(
        f"# DONE-{todo_id} (AUTO-GENERATED by orchestrator)\n"
        f"\n"
        f"The worker finished the stage but did not write a DONE signal (most likely turn-budget\n"
        f"exhaustion before the report-writing step). The orchestrator synthesized this DONE\n"
        f"because ALL configured verify commands (typecheck/build/test) passed AND git changes\n"
        f"were detected vs the baseline. Supervisor review is still recommended; the worker's\n"
        f"own DONE report (design notes, decisions) is absent.\n",
        encoding="utf-8",
    )
    (outbox / f"DONE-{todo_id}.ready").touch()
    return True
