"""Verify commands and auto-DONE logic."""
from __future__ import annotations

import shlex
import subprocess
from pathlib import Path

from . import config as cfg_mod
from . import git_utils
from ._atomic import atomic_write_text


def detect_work_evidence(project_dir: str | Path, baseline_sha: str) -> bool:
    """Return True if there are tracked changes OR untracked files vs baseline."""
    cwd = Path(project_dir)
    if not git_utils.is_git_repo(cwd):
        return False
    if git_utils.has_diff(cwd, baseline_sha):
        return True
    if git_utils.untracked_files(cwd):
        return True
    return False


def run_verify_commands(config: dict, project_dir: str | Path | None = None) -> bool:
    """Run each non-empty verify command. Returns True if all pass.

    ``project_dir`` is forwarded to ``subprocess.run(cwd=...)`` so commands
    like ``pytest`` / ``npm test`` execute in the project, not in the
    orchestrator's CWD. If None, runs in current CWD (legacy behaviour).
    """
    cmd_keys = ["test_cmd", "lint_cmd", "typecheck_cmd", "build_cmd"]
    cmds = []
    for key in cmd_keys:
        val = cfg_mod.get(config, f"verification.{key}", "")
        if val:
            cmds.append(val)

    if not cmds:
        return False  # no commands configured → can't verify

    cwd = str(project_dir) if project_dir is not None else None
    for cmd in cmds:
        parts = shlex.split(cmd)
        if not parts:
            return False
        try:
            result = subprocess.run(
                parts, capture_output=True, check=False, cwd=cwd,
            )
        except (FileNotFoundError, OSError):
            return False
        if result.returncode != 0:
            return False
    return True


def attempt_auto_done(
    project_dir: str | Path,
    todo_id: str,
    config: dict,
    baseline_sha: str,
) -> bool:
    """Try to synthesize DONE when worker left no signal but work + verify pass.

    Returns True if DONE was synthesized.
    """
    cwd = Path(project_dir)
    outbox = cwd / ".agentic" / "outbox"

    # Check automation.auto_done opt-out
    # Auditor HIGH: YAML parses `true` as Python bool True, not string "true".
    # Was: `if auto_done_enabled not in ("true", "1")` — failed for bool.
    auto_done_enabled = cfg_mod.get(config, "automation.auto_done", "true")
    if isinstance(auto_done_enabled, bool):
        if not auto_done_enabled:
            return False
    elif isinstance(auto_done_enabled, str):
        if auto_done_enabled.lower() not in ("true", "1"):
            return False
    elif isinstance(auto_done_enabled, int):
        if auto_done_enabled == 0:
            return False

    # Must have work evidence
    if not detect_work_evidence(cwd, baseline_sha):
        return False

    # Verify commands must all pass (run in project_dir)
    if not run_verify_commands(config, project_dir=project_dir):
        return False

    # Synthesize DONE
    done_md = outbox / f"DONE-{todo_id}.md"
    atomic_write_text(done_md,
        f"# DONE-{todo_id} (AUTO-GENERATED by orchestrator)\n"
        f"\n"
        f"The worker finished the stage but did not write a DONE signal (most likely turn-budget\n"
        f"exhaustion before the report-writing step). The orchestrator synthesized this DONE\n"
        f"because ALL configured verify commands (typecheck/build/test) passed AND git changes\n"
        f"were detected vs the baseline. Supervisor review is still recommended; the worker's\n"
        f"own DONE report (design notes, decisions) is absent.\n",
        encoding="utf-8",
    )
    (outbox / f"DONE-{todo_id}.ready").touch()
    return True
